### ISSUE TITLE
Upload Report completion

### ISSUE THREAD

**Issue by dmange3190** [center-for-threat-informed-defense/tram#114]
How long it takes for the queued report to reach completion ?

**Comment by MarkDavidson** [comment]
Hello @dmange3190 it should only take a minute. If the report is stuck in `QUEUED`, then there is a problem with the processing pipeline. Are you running TRAM via docker or runserver?

**Comment by dmange3190** [comment]
I am running TRAM via docker. Also once the report is in review should I
have to manually accept all the parsed sentences in the report ?

Thanks,
Deep Mange

**Comment by MarkDavidson** [comment]
Since you are running TRAM via docker, if the pipeline is not working then there might be a TRAM-level bug. If you think this is the case I can tell you how to get logs off the system to troubleshoot.

You have to manually accept all of the parsed sentences. The workflow that TRAM was designed around is that the AI/ML _proposes_ mappings, but a human analyst needs to validate/accept them.

**Comment by dmange3190** [comment]
Ok, thanks for the clarification.

Thanks,
Deep Mange

**Comment by ghostpepper108** [comment]
I think I am facing the same problem when using docker-compose. After I submit the pdf, it perpetually stays in "Queued" status. Sometimes, after restarting the portal with docker-compose, it generates the report but not sure if it completed its job.
