### ISSUE TITLE
Older version was better

### ISSUE THREAD

**Issue by ghostpepper108** [center-for-threat-informed-defense/tram#141]
It looks like the previous version of TRAM (https://github.com/mitre-attack/tram) had lot more features compared to the current version like mapping with Navigator, Analyzing URLs, video tutorials/blogs on how to use it etc and now these features are "enhancement" requests. I understand that it was a redesign but it would have been good if the project moved forward and retained what was already there? The current version looks half-baked with enhancements taking a long time.

**Comment by MarkDavidson** [comment]
Hello @ghostpepper108 and thank you for your comments.

TRAM is a community project that the Center for Threat-Informed Defense maintains. Within our resources, we do our best to make continual progress on community contributions, bugs, and features. I understand this isn't fast enough for everyone. That said, we have done 3 releases since September and have added many important new features including Dockerization and separating the GUI from the ML Pipeline into separate processes.

I thank you for bringing this to the community's attention. I am closing this issue since it's not something that can be resolved in code.

If you want to reach out to ctid@mitre-engenuity.org, I am happy to help identify any features you need or bugs you are seeing and get them recoded in the issue list and perhaps acted on.

Thank you!
